services:
  database:
    container_name: "db"
    image: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - "./.env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      POSTGRES_TIMEZONE: ${POSTGRES_TIMEZONE}